### ISSUE TITLE
Add All & Every function

### ISSUE THREAD

**Issue by aswinkarthik** [thecasualcoder/godash#5]
Behaviour for the both the functions are same. 

## All/Every

Returns true if the predicate passes for **all** of the element in the slice. Make Every as an alias of All. This is to retain terminology of lodash.

API

```go
input := []int{3,6,9,12,15}

output := godash.All(input, func(element int) bool {
   return element % 3 == 0
})

// output is true
```

**Comment by pearl2201** [comment]
Could I implement it :D

**Comment by karuppiah7890** [comment]
Sure go ahead! 👍
